app = "omix-sms"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  CACHE_DRIVER = "redis"
  QUEUE_CONNECTION = "redis"
  SESSION_DRIVER = "cookie"
  BROADCAST_DRIVER = "log"

[processes]
  app = ""
  worker = "php artisan queue:work"

[mounts]
  source = "storage"
  destination = "/var/www/html/storage"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  min_machines_running = 0

  [[http_service.concurrency]]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[checks]
  [checks.healthz]
    port = 8080
    type = "http"
    interval = "30s"
    grace_period = "5s"
    method = "GET"
    path = "/healthz"
    timeout = "5s"

[[statics]]
  guest_path = "/var/www/html/public"
  url_prefix = "/"
